Repository ines/spacy-course, pull requests merged in 2020-06, with the labels that each got.

#64 Don't hard-code arbitrary iteration variable in 1.9
  exercises/de/test_01_09.py
  exercises/en/test_01_09.py
  exercises/es/test_01_09.py
  exercises/ja/test_01_09.py
Labels: enhancement, tests

#65 Fix a typo
  locale.json
Labels: lang / ja

#70 Fix typos in slides and adjust tests and exercises to spacy v2.3
  chapters/es/chapter1.md
  chapters/es/chapter2.md
  chapters/es/slides/chapter1_02_statistical-models.md
  chapters/es/slides/chapter1_03_rule-based-matching.md
  chapters/es/slides/chapter2_03_word-vectors-similarity.md
  chapters/es/slides/chapter2_04_models-rules.md
  chapters/es/slides/chapter3_01_processing-pipelines.md
  chapters/es/slides/chapter3_04_scaling-performance.md
  chapters/es/slides/chapter4_02_training-loop.md
  chapters/es/slides/chapter4_03_training-best-practices.md
  chapters/es/slides/chapter4_04_wrapping-up.md
  exercises/es/exc_01_04.py
  exercises/es/exc_01_09.py
  exercises/es/exc_01_11.py
  exercises/es/exc_02_13.py
  exercises/es/solution_01_04.py
  exercises/es/solution_01_09.py
  exercises/es/solution_01_11.py
  exercises/es/solution_02_13.py
  exercises/es/test_01_09.py
  exercises/es/test_01_11.py
  exercises/es/test_02_13.py
  exercises/es/test_general.py
Labels: enhancement, lang / es

#69 Update for spaCy v2.3
  binder/requirements.txt
  chapters/de/chapter1.md
  chapters/es/chapter1.md
  chapters/es/chapter2.md
  chapters/es/slides/chapter1_02_statistical-models.md
  chapters/es/slides/chapter1_03_rule-based-matching.md
  chapters/es/slides/chapter2_03_word-vectors-similarity.md
  chapters/es/slides/chapter2_04_models-rules.md
  chapters/es/slides/chapter3_01_processing-pipelines.md
  chapters/es/slides/chapter3_04_scaling-performance.md
  chapters/es/slides/chapter4_02_training-loop.md
  chapters/es/slides/chapter4_03_training-best-practices.md
  chapters/es/slides/chapter4_04_wrapping-up.md
  exercises/de/exc_01_09.py
  exercises/de/solution_01_09.py
  exercises/de/test_01_09.py
  exercises/de/test_general.py
  exercises/es/exc_01_04.py
  exercises/es/exc_01_09.py
  exercises/es/exc_01_11.py
  exercises/es/exc_02_13.py
  exercises/es/solution_01_04.py
  exercises/es/solution_01_09.py
  exercises/es/solution_01_11.py
  exercises/es/solution_02_13.py
  exercises/es/test_01_09.py
  exercises/es/test_01_11.py
  exercises/es/test_02_13.py
  exercises/es/test_general.py
  meta.json
Labels: content, enhancement, lang / de, lang / en, lang / es

#72 ✏️ Add note Chapter 1 lesson 1 about definitions
  chapters/es/slides/chapter1_01_introduction-to-spacy.md
Labels: content, lang / es

#73 🎬 Add Spanish video and timestamps
  chapters/es/chapter1.md
  chapters/es/chapter2.md
  chapters/es/chapter3.md
  chapters/es/chapter4.md
  locale.json
Labels: enhancement, lang / es

#74 fix typo
  chapters/es/slides/chapter3_04_scaling-performance.md
Labels: lang / es
